# Generated by Django 4.1.7 on 2023-03-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
